apiVersion: v1
kind: Service
metadata:
  name: traffic-control-backend
  labels:
    app: traffic-control
    component: backend
spec:
  selector:
    app: traffic-control
    component: backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
