apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traffic-control

resources:
  - namespace.yaml
  - buildconfig.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - route.yaml

configMapGenerator:
  - name: traffic-control-config
    literals:
      - VLLM_REPLICA_1_URL=http://vllm-server.user-sbowerma.svc.cluster.local:8000/v1
      - VLLM_REPLICA_2_URL=http://vllm-server.user-sbowerma.svc.cluster.local:8000/v1
      - VLLM_REPLICA_3_URL=http://vllm-server.user-sbowerma.svc.cluster.local:8000/v1
      - MODEL_NAME=RedHatAI/Mistral-Small-24B-Instruct-2501-quantized.w4a16
